# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'evo-web-example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for evo-web-example
  pod 'EvoPayments', :path => '../../'
end
